# Generated by Django 5.2 on 2025-05-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
