# Generated by Django 5.2 on 2025-05-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
