# Generated by Django 5.2 on 2025-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], max_length=10),
        ),
    ]
